#!/usr/bin/env python3
"""Regenerate embedded Vulkan shaders: --dxc /path/to/Microsoft/DXC.

DXC is a development dependency only. No SDK or shader files ship at runtime.
"""
import argparse
from pathlib import Path
import struct
import subprocess
import tempfile

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--dxc',default='dxc')
    args=parser.parse_args()
    root=Path(__file__).resolve().parent.parent
    for name in ['terrain','fields']:
        with tempfile.TemporaryDirectory(prefix='urban-shaders-') as directory:
            output=Path(directory)/(name+'.spv')
            subprocess.run([args.dxc,'-spirv','-T','cs_6_0','-E','main','-O3',
                '-fspv-target-env=vulkan1.1',str(root/('src/sc_gpu_'+name+'.hlsl')),'-Fo',str(output)],check=True)
            data=output.read_bytes()
        assert len(data)%4==0 and data[:4]==b'\x03\x02\x23\x07','Invalid SPIR-V header'
        words=struct.unpack('<'+'I'*(len(data)//4),data)
        lines=['/* Generated by tools/compile_gpu_shaders.py from sc_gpu_'+name+'.hlsl. */',
            '#pragma once','#include <stdint.h>','static const uint32_t sc_gpu_'+name+'_spirv[] = {']
        lines.extend('    '+','.join(f'0x{word:08x}u' for word in words[i:i+8])+',' for i in range(0,len(words),8))
        lines.append('};')
        (root/('src/sc_gpu_'+name+'_spirv.h')).write_text('\n'.join(lines)+'\n')
        print(f'Embedded {name} shader: {len(data)} SPIR-V bytes')

if __name__=='__main__': main()
