"""Compile conservative host-hook ownership from source, without ROM data.

Every literal PC in the coordinate/geometry functions is admitted. Including
return PCs and mask constants deliberately produces harmless false positives;
an ordinary instruction with no such PC cannot have a hook side effect.
"""
from pathlib import Path
import argparse, hashlib, re

root = Path(__file__).resolve().parent.parent
p = argparse.ArgumentParser()
p.add_argument('--check', action='store_true')
a = p.parse_args()
source = (root / 'src/sc_world_guest.c').read_text()
sections = [source[source.index('static bool huge_step('):source.index('void ScWorldGuestVehicles(')],
            source[source.index('static unsigned big_dimension(uint32_t pc) {'):source.index('static unsigned dimension(const ScWorld *w,uint32_t pc) {')]]
vehicle = source[source.index('void ScWorldGuestVehicles('):source.index('/* Verified map geometry only;')]
def bitmap(text):
    data = bytearray(4096)
    for literal in re.findall(r'0x[0-9a-fA-F]+', text):
        pc = int(literal, 16) & 65535
        if pc >= 32768:
            pc -= 32768
            data[pc // 8] |= 1 << (pc % 8)
    return data
result = '/* Generated by tools/compile_world_layout.py from host source; no ROM content. */\n#pragma once\n'
for name, text in [('sc_world_step_sites', '\n'.join(sections)), ('sc_world_vehicle_sites', vehicle)]:
    result += f'static const uint8_t {name}[4096]={{\n'
    result += ''.join(f'    [{i}]=0x{v:02x},\n' for i, v in enumerate(bitmap(text)) if v)
    result += '};\n'
result += f'/* Ownership source SHA256: {hashlib.sha256(chr(10).join(sections + [vehicle]).encode()).hexdigest()} */\n'
output = root / 'src/sc_world_guest_layout.h'
if a.check:
    assert output.read_text() == result, 'Regenerate world hook ownership before building'
else:
    output.write_text(result)
